#!/bin/bash
if (env | grep -Fq SLURM || env | grep -Fq TACC)
then
  for f in $(squeue -u $USER | grep $USER | awk '{print $1}')
  do
  echo $f
  scontrol show jobid $f | grep Command | cut -d '=' -f 2
  done
fi

